name: "Setup osxcross"
author: mbround18
description: Setup osxcross for rust/other compilation projects.
inputs:
  osx-version:
    description: "Version of osx to use."
    required: true

#  Set CARGO_TARGET_X86_64_APPLE_DARWIN_RUSTFLAGS = "-C linker=x86_64-apple-darwin${version}-linker -C linker=x86_64-apple-darwin${version}-ar -C link-arg=-undefined -C link-arg=dynamic_lookup"
# echo "{environment_variable_name}={value}" >> $GITHUB_ENV

runs:
  using: "composite"
  steps:
    - shell: bash
      name: Check system
      run: |
        if [[ "$OSTYPE" == "linux-gnu"* ]]; then
          echo "Found linux based system, proceeding."
          if [ -z "${{ inputs.osx-version }}" ]; then
            echo "Error!: Osx Version required!"
            exit 1
          fi
        else
          echo "Error!: Your system must be a linux based system! Try running this on ubuntu-latest."
          exit 1
        fi
    # - uses: ATiltedTree/setup-rust@v1
    - shell: bash
      run: mkdir -p $GITHUB_ACTION_PATH/osxcross

    - shell: bash
      id: target
      run: |
        echo "::group::Installing Deps"
        sudo apt-get install -y -qq clang gcc g++ zlib1g-dev libmpc-dev libmpfr-dev libgmp-dev
        echo "::endgroup::"

        OSXCROSS_FOLDER="$(echo "$GITHUB_ACTION_PATH/osxcross" | sed 's/.\///')"

        echo "$OSXCROSS_FOLDER"

        exit 1

        echo "::group::Cloning osxcross"
        git clone https://github.com/tpoechtrager/osxcross "$OSXCROSS_FOLDER"
        echo "::endgroup::"


        # Check setup for osx version

        echo "::group::Fetching macosx SDK"
        FILE_NAME="MacOSX${{ inputs.osx-version }}.sdk.tar.xz"

        # Check joseluisq/macosx-sdks for release
        wget -nc "https://github.com/joseluisq/macosx-sdks/releases/download/${{ inputs.osx-version }}/${FILE_NAME}" -O "$OSXCROSS_FOLDER/tarballs/${FILE_NAME}"
        echo "::endgroup::"


        echo "Folder=${OSXCROSS_FOLDER}"
        echo "::set-output name=target::${OSXCROSS_FOLDER}/target"


    - uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-osxcross-${{ inputs.osx-version }}
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ${{ steps.target.outputs.target }}

    - shell: bash
      env:
        SDK_VERSION: "${{ inputs.osx-version }}"
        UNATTENDED: "yes"
      run: |
        cd "$GITHUB_ACTION_PATH/osxcross"
        bash ./build.sh

    - shell: bash
      run: |
        echo "$GITHUB_ACTION_PATH/osxcross/target/bin" >> $GITHUB_PATH
        LINKER_FILE="$(find "$GITHUB_ACTION_PATH/osxcross/target/bin" -name "x86_64-apple-darwin*-linker")"
        AR_FILE="$(find "$GITHUB_ACTION_PATH/osxcross/target/bin" -name "x86_64-apple-darwin*-ar")"
        echo "Setting: CARGO_TARGET_X86_64_APPLE_DARWIN_RUSTFLAGS=\"-C linker=${AR_FILE} -C linker=${LINKER_FILE} -C link-arg=-undefined -C link-arg=dynamic_lookup\""
        echo "CARGO_TARGET_X86_64_APPLE_DARWIN_RUSTFLAGS=\"-C linker=${AR_FILE} -C linker=${LINKER_FILE} -C link-arg=-undefined -C link-arg=dynamic_lookup\"" >> $GITHUB_ENV
