name: Demo Workflow
on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ATiltedTree/setup-rust@v1
        with:
          targets: x86_64-apple-darwin
          rust-version: nightly

      - uses: ./
        with:
          osx-version: "12.3"

      - name: Cloning Hello World
        run: git clone https://github.com/mbround18/rs-simple-hello-world
    
      - name: Build Hello World
        working_directory: ./rs-simple-hello-world 
        run: cargo build --release --target x86_64-apple-darwin
        
          
